# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# Docs: https://docs.coderabbit.ai/getting-started/configure-coderabbit

inheritance: true

reviews:
  # Generate walkthrough in a Markdown collapsible section.
  # default: false
  collapse_walkthrough: true

  # Automatically apply the suggested labels to the PR/MR.
  # default: false
  auto_apply_labels: true

  # Generate a poem in the walkthrough comment.
  # default: true
  poem: false # :-(
