# Copyright 2025 Specter Ops, Inc.
#
# Licensed under the Apache License, Version 2.0
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Run Go Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - "stage/**"
    types:
      - opened
      - synchronize

jobs:
  run-go-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code for this repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          check-latest: true

      - name: Run Tests
        run: |
          go tool stbernard test -g -r

      - name: Install AllureCtl 
        # v0.14.3
        run: | 
          go install github.com/robotomize/go-allure/cmd/golurectl@8ef44907de4280d459f93ce6660b28e263b1d6bc
      
      - name: Building Allure JSON 
        run: |
          mkdir allure-results
          cat go-test-results.json | golurectl -l -e --allure-suite "Go Test" --allure-tags "Unit" -o ./allure-results
      - name: Neo4j Debug Logs
        if: failure()
        run: |
          docker compose -f docker-compose.testing.yml exec -T testgraph cat /logs/debug.log

      - name: Postgres Debug Logs
        if: failure()
        run: |
          docker compose -f docker-compose.testing.yml logs testdb

      - name: Stop and Remove Containers
        if: ${{ ! cancelled() }}
        run: |
          docker compose -f docker-compose.testing.yml down
      
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: allure-results
          path: allure-results